# Generated by Django 2.1.5 on 2019-02-10 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhostel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myhostel',
            options={'managed': True},
        ),
    ]
